### ISSUE TITLE
Section 6 - does kdcnonce need to be provided on a token post from a monitor-only?

### ISSUE THREAD

**Issue by marco-tiloca-sics** [ace-wg/ace-key-groupcomm-oscore#34]

**Comment by marco-tiloca-sics** [comment]
It's not needed if the token authorizes the client to be only monitor in all the groups covered in the token.

Is it worth addressing and implementing this optimization? Or rather to just return a kdcnonce even in such a case, even thoug that joining node is not going to use the received kdcnonce to build a signature challenge?

**Comment by jimsch** [comment]
I don't know if it is worth it or not, that is a question that could be left to the implementer if it the field is optional rather than required.
